import datetime
import random

from django.core.management.base import BaseCommand
from django.utils import timezone

from store.models import Category, Medicine

CATEGORIES = [
    ("Pain Relief", "💊", "Painkillers and anti-inflammatory medicines"),
    ("Fever & Cold", "🤒", "Fever, cold and flu relief"),
    ("Antibiotics", "🧫", "Prescription antibiotics for infections"),
    ("Vitamins & Supplements", "🍊", "Daily vitamins, minerals and supplements"),
    ("Digestive Health", "🌿", "Antacids, laxatives and gut health"),
    ("Diabetes Care", "🩸", "Blood-sugar management"),
    ("Heart & Blood Pressure", "❤️", "Cardiac and BP management"),
    ("Skin Care", "🧴", "Dermatology creams and ointments"),
    ("Allergy", "🤧", "Antihistamines and allergy relief"),
    ("Respiratory", "🫁", "Cough, asthma and breathing relief"),
    ("First Aid", "🩹", "Wound care and emergency essentials"),
    ("Baby & Mother Care", "🍼", "Infant and maternal health"),
]

MEDICINES = [
    dict(name="Paracetamol 650", company="Cipla", category="Pain Relief", form="tablet",
         composition="Paracetamol 650mg",
         description="A widely used analgesic and antipyretic for fast relief from pain and fever.",
         uses="Fever\nHeadache\nBody ache\nToothache\nMenstrual cramps",
         dosage="1 tablet every 6-8 hours after food. Do not exceed 4 tablets in 24 hours.",
         side_effects="Nausea\nStomach upset\nSkin rash (rare)",
         precautions="Avoid alcohol\nDo not exceed recommended dose\nConsult doctor if fever persists beyond 3 days",
         price=35, quantity=250, requires_prescription=False, emoji="💊"),
    dict(name="Azithromycin 500", company="Sun Pharma", category="Antibiotics", form="tablet",
         composition="Azithromycin 500mg",
         description="A macrolide antibiotic used to treat a variety of bacterial infections.",
         uses="Respiratory tract infection\nSkin infection\nEar infection\nTyphoid",
         dosage="1 tablet once daily for 3 days, or as prescribed by your doctor.",
         side_effects="Diarrhea\nNausea\nAbdominal pain\nHeadache",
         precautions="Complete the full course as prescribed\nInform doctor of liver conditions\nNot for self-medication",
         price=118, quantity=60, requires_prescription=True, emoji="💊"),
    dict(name="Vitamin C 500mg Chewable", company="HealthKart", category="Vitamins & Supplements", form="tablet",
         composition="Ascorbic Acid 500mg",
         description="Chewable orange-flavoured Vitamin C tablets to support immunity and skin health.",
         uses="Immunity support\nAntioxidant\nSkin health\nCold prevention",
         dosage="1 tablet daily after breakfast.",
         side_effects="Mild stomach upset in high doses",
         precautions="Consult doctor if you have kidney stones history",
         price=180, quantity=300, requires_prescription=False, emoji="🍊"),
    dict(name="Cetirizine 10mg", company="Glenmark", category="Allergy", form="tablet",
         composition="Cetirizine Hydrochloride 10mg",
         description="A second-generation antihistamine that relieves allergy symptoms with low drowsiness.",
         uses="Sneezing\nRunny nose\nItchy eyes\nHives\nSkin allergy",
         dosage="1 tablet once daily, preferably at night.",
         side_effects="Drowsiness\nDry mouth\nFatigue",
         precautions="Avoid driving if drowsy\nUse with caution in elderly patients",
         price=28, quantity=400, requires_prescription=False, emoji="🤧"),
    dict(name="Amoxicillin 500", company="Alkem Labs", category="Antibiotics", form="capsule",
         composition="Amoxicillin 500mg",
         description="A broad-spectrum penicillin antibiotic for common bacterial infections.",
         uses="Throat infection\nUrinary tract infection\nChest infection\nDental infection",
         dosage="1 capsule three times a day for 5-7 days as prescribed.",
         side_effects="Diarrhea\nNausea\nRash\nAllergic reactions (rare)",
         precautions="Inform doctor of penicillin allergy\nComplete full course",
         price=95, quantity=45, requires_prescription=True, emoji="💊"),
    dict(name="Metformin 500", company="USV Ltd", category="Diabetes Care", form="tablet",
         composition="Metformin Hydrochloride 500mg",
         description="First-line oral medication to control blood sugar levels in type-2 diabetes.",
         uses="Type 2 diabetes\nBlood sugar control\nPCOS management (as advised)",
         dosage="1 tablet with breakfast and dinner, or as prescribed.",
         side_effects="Nausea\nDiarrhea\nMetallic taste\nVitamin B12 deficiency (long term use)",
         precautions="Take with food\nRegular blood sugar monitoring required\nAvoid in kidney disease",
         price=42, quantity=180, requires_prescription=True, emoji="🩸"),
    dict(name="Amlodipine 5mg", company="Torrent Pharma", category="Heart & Blood Pressure", form="tablet",
         composition="Amlodipine Besylate 5mg",
         description="A calcium channel blocker used to treat high blood pressure and chest pain (angina).",
         uses="Hypertension\nAngina\nCoronary artery disease",
         dosage="1 tablet once daily, same time every day.",
         side_effects="Swelling of ankles\nDizziness\nFlushing\nFatigue",
         precautions="Do not stop abruptly\nMonitor blood pressure regularly",
         price=54, quantity=150, requires_prescription=True, emoji="❤️"),
    dict(name="Pantoprazole 40mg", company="Sun Pharma", category="Digestive Health", form="tablet",
         composition="Pantoprazole 40mg",
         description="A proton pump inhibitor that reduces stomach acid to relieve acidity and heartburn.",
         uses="Acidity\nGERD\nStomach ulcers\nHeartburn",
         dosage="1 tablet daily before breakfast on an empty stomach.",
         side_effects="Headache\nDiarrhea\nNausea",
         precautions="Long-term use should be monitored by a doctor",
         price=68, quantity=220, requires_prescription=False, emoji="🌿"),
    dict(name="ORS Electrolyte Powder", company="FDC Limited", category="Digestive Health", form="powder",
         composition="Oral Rehydration Salts (WHO formula)",
         description="Rehydration solution to replace fluids and electrolytes lost due to diarrhea or vomiting.",
         uses="Dehydration\nDiarrhea\nHeat exhaustion\nVomiting",
         dosage="Dissolve 1 sachet in 200ml clean water; drink after every loose motion.",
         side_effects="Rare if used as directed",
         precautions="Use freshly prepared solution within 24 hours\nDiscard unused solution after a day",
         price=20, quantity=500, requires_prescription=False, emoji="🌿"),
    dict(name="Ibuprofen 400mg", company="Abbott", category="Pain Relief", form="tablet",
         composition="Ibuprofen 400mg",
         description="A non-steroidal anti-inflammatory drug (NSAID) for pain, inflammation and fever.",
         uses="Muscle pain\nJoint pain\nArthritis\nFever\nMenstrual pain",
         dosage="1 tablet every 6-8 hours after food, not exceeding 3 tablets/day.",
         side_effects="Stomach upset\nHeartburn\nDizziness",
         precautions="Take after food\nAvoid in peptic ulcer or kidney disease\nAvoid with blood thinners",
         price=45, quantity=210, requires_prescription=False, emoji="💊"),
    dict(name="Dolo 650", company="Micro Labs", category="Fever & Cold", form="tablet",
         composition="Paracetamol 650mg",
         description="A trusted fever and pain reliever suitable for adults.",
         uses="Fever\nCold-related body ache\nHeadache",
         dosage="1 tablet every 6 hours after food, maximum 4 tablets a day.",
         side_effects="Rare when taken as directed\nNausea in high doses",
         precautions="Avoid alcohol\nDo not combine with other paracetamol products",
         price=30, quantity=300, requires_prescription=False, emoji="🤒"),
    dict(name="Vicks Cough Syrup", company="P&G Health", category="Respiratory", form="syrup",
         composition="Dextromethorphan + Menthol",
         description="Soothing cough syrup that calms dry cough and throat irritation.",
         uses="Dry cough\nThroat irritation\nCold-related cough",
         dosage="10ml every 6-8 hours, or as directed on the label.",
         side_effects="Drowsiness\nMild nausea",
         precautions="Not recommended for children under 6\nAvoid driving after taking",
         price=110, quantity=140, requires_prescription=False, emoji="🫁"),
    dict(name="Asthalin Inhaler", company="Cipla", category="Respiratory", form="device",
         composition="Salbutamol 100mcg/dose",
         description="A fast-acting bronchodilator inhaler for quick relief from breathlessness and wheezing.",
         uses="Asthma\nBronchospasm\nCOPD relief",
         dosage="1-2 puffs as needed, maximum as advised by physician.",
         side_effects="Tremors\nFast heartbeat\nNervousness",
         precautions="Keep inhaler technique correct\nCarry at all times if asthmatic\nSeek help if overused",
         price=165, quantity=90, requires_prescription=True, emoji="🫁"),
    dict(name="Calcium + Vitamin D3", company="Mankind Pharma", category="Vitamins & Supplements", form="tablet",
         composition="Calcium Carbonate 500mg + Vitamin D3 250IU",
         description="Supports bone health, especially useful for women and the elderly.",
         uses="Bone health\nOsteoporosis prevention\nCalcium deficiency",
         dosage="1 tablet daily after a meal.",
         side_effects="Constipation\nBloating",
         precautions="Avoid in hypercalcemia\nTake with plenty of water",
         price=145, quantity=260, requires_prescription=False, emoji="🍊"),
    dict(name="Multivitamin Daily", company="Himalaya", category="Vitamins & Supplements", form="tablet",
         composition="Multivitamins + Multiminerals",
         description="A complete daily multivitamin to support energy, immunity and overall wellness.",
         uses="General wellness\nFatigue\nNutritional support",
         dosage="1 tablet daily after breakfast.",
         side_effects="Mild nausea if taken empty stomach",
         precautions="Not a substitute for a balanced diet",
         price=210, quantity=300, requires_prescription=False, emoji="🍊"),
    dict(name="Betadine Antiseptic Ointment", company="Win-Medicare", category="First Aid", form="ointment",
         composition="Povidone Iodine 5% w/w",
         description="Antiseptic ointment for minor cuts, wounds, and burns to prevent infection.",
         uses="Minor cuts\nWounds\nBurns\nAbrasions",
         dosage="Apply a thin layer to the affected area 2-3 times daily.",
         side_effects="Mild skin irritation\nAllergic reaction (rare)",
         precautions="For external use only\nAvoid contact with eyes",
         price=85, quantity=180, requires_prescription=False, emoji="🩹"),
    dict(name="Digital Thermometer", company="Dr. Trust", category="First Aid", form="device",
         composition="Electronic sensor device",
         description="Fast and accurate digital thermometer for oral, underarm or rectal temperature checks.",
         uses="Fever monitoring\nHome healthcare",
         dosage="Follow device instructions; typical reading in 30-60 seconds.",
         side_effects="Not applicable",
         precautions="Clean probe before and after each use",
         price=249, quantity=120, requires_prescription=False, emoji="🩹"),
    dict(name="Cofsils Lozenges", company="Sunofi", category="Fever & Cold", form="tablet",
         composition="Menthol + Eucalyptus Oil",
         description="Soothing throat lozenges that relieve sore throat and cough irritation.",
         uses="Sore throat\nThroat irritation\nMild cough",
         dosage="Let 1 lozenge dissolve slowly in the mouth every 2-3 hours as needed.",
         side_effects="Mild tingling sensation",
         precautions="Not for children under 5 years",
         price=40, quantity=260, requires_prescription=False, emoji="🤒"),
    dict(name="Losartan 50mg", company="Sun Pharma", category="Heart & Blood Pressure", form="tablet",
         composition="Losartan Potassium 50mg",
         description="An angiotensin receptor blocker (ARB) used to manage high blood pressure.",
         uses="Hypertension\nDiabetic kidney protection",
         dosage="1 tablet once daily, or as prescribed.",
         side_effects="Dizziness\nFatigue\nHigh potassium levels",
         precautions="Regular kidney function monitoring advised\nAvoid in pregnancy",
         price=62, quantity=140, requires_prescription=True, emoji="❤️"),
    dict(name="Atorvastatin 10mg", company="Zydus Cadila", category="Heart & Blood Pressure", form="tablet",
         composition="Atorvastatin Calcium 10mg",
         description="A statin medication that lowers LDL cholesterol and reduces cardiovascular risk.",
         uses="High cholesterol\nCardiovascular disease prevention",
         dosage="1 tablet once daily at bedtime, or as prescribed.",
         side_effects="Muscle pain\nDigestive issues\nLiver enzyme changes",
         precautions="Periodic liver function tests recommended\nAvoid grapefruit juice",
         price=88, quantity=160, requires_prescription=True, emoji="❤️"),
    dict(name="Insulin Glargine Injection", company="Biocon", category="Diabetes Care", form="injection",
         composition="Insulin Glargine 100IU/ml",
         description="A long-acting insulin analogue providing steady blood sugar control over 24 hours.",
         uses="Type 1 diabetes\nType 2 diabetes requiring insulin",
         dosage="As prescribed by physician, typically once daily subcutaneous injection.",
         side_effects="Hypoglycemia\nInjection site reaction\nWeight gain",
         precautions="Rotate injection sites\nMonitor blood sugar closely\nStore in refrigerator",
         price=485, quantity=40, requires_prescription=True, emoji="🩸"),
    dict(name="Glucometer Test Strips", company="Accu-Chek", category="Diabetes Care", form="device",
         composition="Glucose oxidase test strips",
         description="Test strips for accurate at-home blood glucose monitoring, compatible with Accu-Chek meters.",
         uses="Blood sugar self-monitoring",
         dosage="Use as per glucometer instructions, one strip per test.",
         side_effects="Not applicable",
         precautions="Store in a cool dry place\nCheck expiry before use",
         price=650, quantity=90, requires_prescription=False, emoji="🩸"),
    dict(name="Clotrimazole Cream", company="Bayer", category="Skin Care", form="ointment",
         composition="Clotrimazole 1% w/w",
         description="An antifungal cream effective against ringworm, athlete's foot and yeast infections.",
         uses="Ringworm\nAthlete's foot\nFungal skin infections",
         dosage="Apply a thin layer to affected area twice daily for 2-4 weeks.",
         side_effects="Mild burning\nRedness\nItching",
         precautions="For external use only\nComplete full treatment duration",
         price=75, quantity=200, requires_prescription=False, emoji="🧴"),
    dict(name="Sunscreen SPF 50", company="Neutrogena", category="Skin Care", form="ointment",
         composition="Broad spectrum UVA/UVB filters SPF 50",
         description="Lightweight, non-greasy sunscreen offering broad-spectrum protection for daily use.",
         uses="Sun protection\nPrevent tanning\nSkin ageing prevention",
         dosage="Apply generously 15-20 minutes before sun exposure; reapply every 3-4 hours.",
         side_effects="Mild skin irritation in sensitive skin",
         precautions="Avoid contact with eyes\nPatch test recommended for sensitive skin",
         price=399, quantity=170, requires_prescription=False, emoji="🧴"),
    dict(name="Folic Acid 5mg", company="Mankind Pharma", category="Baby & Mother Care", form="tablet",
         composition="Folic Acid 5mg",
         description="Essential supplement for expecting mothers to support healthy fetal development.",
         uses="Pregnancy nutrition\nFolate deficiency\nAnaemia prevention",
         dosage="1 tablet daily, or as advised by your gynaecologist.",
         side_effects="Rare; mild nausea",
         precautions="Best started before conception\nFollow doctor's dosage advice",
         price=25, quantity=240, requires_prescription=False, emoji="🍼"),
    dict(name="Gripe Water", company="Woodward's", category="Baby & Mother Care", form="syrup",
         composition="Dill Oil + Sodium Bicarbonate",
         description="A gentle formula to relieve infant colic, gas and hiccups.",
         uses="Infant colic\nGas\nHiccups",
         dosage="1 teaspoon (5ml) after feeds, up to 6 times a day, or as advised by paediatrician.",
         side_effects="Rare when used as directed",
         precautions="Consult paediatrician before use in infants under 1 month",
         price=95, quantity=160, requires_prescription=False, emoji="🍼"),
    dict(name="Diaper Rash Cream", company="Johnson's Baby", category="Baby & Mother Care", form="ointment",
         composition="Zinc Oxide 15%",
         description="Protective barrier cream to soothe and prevent diaper rash in babies.",
         uses="Diaper rash\nSkin chafing\nMoisture barrier",
         dosage="Apply a thin layer at each diaper change.",
         side_effects="Rare; mild irritation",
         precautions="For external use only\nDiscontinue if rash worsens",
         price=180, quantity=210, requires_prescription=False, emoji="🍼"),
    dict(name="Loratadine 10mg", company="Dr. Reddy's", category="Allergy", form="tablet",
         composition="Loratadine 10mg",
         description="A non-drowsy antihistamine for effective, long-lasting allergy relief.",
         uses="Seasonal allergies\nHay fever\nChronic hives",
         dosage="1 tablet once daily.",
         side_effects="Headache\nDry mouth\nFatigue (rare)",
         precautions="Use with caution in liver impairment",
         price=32, quantity=280, requires_prescription=False, emoji="🤧"),
    dict(name="Montelukast 10mg", company="Cipla", category="Respiratory", form="tablet",
         composition="Montelukast Sodium 10mg",
         description="Used to prevent asthma attacks and relieve allergic rhinitis symptoms.",
         uses="Asthma prevention\nAllergic rhinitis",
         dosage="1 tablet once daily in the evening, or as prescribed.",
         side_effects="Headache\nStomach pain\nMood changes (rare)",
         precautions="Not for acute asthma attacks\nReport any mood changes to doctor",
         price=115, quantity=100, requires_prescription=True, emoji="🫁"),
    dict(name="Omeprazole 20mg", company="Dr. Reddy's", category="Digestive Health", form="capsule",
         composition="Omeprazole 20mg",
         description="Reduces stomach acid production to treat acidity, ulcers and reflux disease.",
         uses="Acid reflux\nGastric ulcers\nHeartburn",
         dosage="1 capsule daily before breakfast, on an empty stomach.",
         side_effects="Headache\nDiarrhea\nStomach pain",
         precautions="Avoid long-term use without medical supervision",
         price=58, quantity=200, requires_prescription=False, emoji="🌿"),
    dict(name="Iron + Folic Acid Tablets", company="Abbott", category="Vitamins & Supplements", form="tablet",
         composition="Ferrous Sulphate 150mg + Folic Acid 0.5mg",
         description="Supports healthy red blood cell production and helps prevent iron-deficiency anaemia.",
         uses="Iron deficiency anaemia\nGeneral fatigue\nPregnancy nutrition",
         dosage="1 tablet daily after food, or as advised by your doctor.",
         side_effects="Constipation\nDark stools\nNausea",
         precautions="Take with vitamin C rich food for better absorption\nAvoid with tea/coffee",
         price=48, quantity=230, requires_prescription=False, emoji="🍊"),
]


class Command(BaseCommand):
    help = "Seed the database with pharmacy categories and a realistic medicine catalogue."

    def add_arguments(self, parser):
        parser.add_argument("--flush", action="store_true", help="Delete existing medicines and categories first")

    def handle(self, *args, **options):
        if options["flush"]:
            Medicine.objects.all().delete()
            Category.objects.all().delete()
            self.stdout.write(self.style.WARNING("Cleared existing medicines and categories."))

        category_map = {}
        for name, icon, desc in CATEGORIES:
            cat, created = Category.objects.get_or_create(name=name, defaults={"icon": icon, "description": desc})
            category_map[name] = cat
            if created:
                self.stdout.write(f"Created category: {name}")

        today = timezone.localdate()
        created_count = 0
        for med in MEDICINES:
            if Medicine.objects.filter(name=med["name"]).exists():
                continue
            expiry_days = random.randint(60, 900)
            Medicine.objects.create(
                name=med["name"],
                company=med["company"],
                category=category_map[med["category"]],
                form=med["form"],
                composition=med["composition"],
                description=med["description"],
                uses=med["uses"],
                dosage=med["dosage"],
                side_effects=med["side_effects"],
                precautions=med["precautions"],
                price=med["price"],
                quantity=med["quantity"],
                expiry=today + datetime.timedelta(days=expiry_days),
                batch_no=f"BN{random.randint(10000, 99999)}",
                requires_prescription=med["requires_prescription"],
                image_emoji=med["emoji"],
            )
            created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Seeding complete. {created_count} new medicines added across {len(CATEGORIES)} categories."
        ))
